language: java
jdk:
  - oraclejdk8

services:
  - mongodb

sudo: false

before_install:
- mvn clean
- mvn install -Dmaven.test.skip=true
- mvn test

install: true

after_success:
- cd vokter-core
- mvn jacoco:report coveralls:report