language: java
jdk:
  - oraclejdk8

services:
  - mongodb

before_install:
- mvn clean
- mvn install -Dmaven.test.skip=true
- mvn test

install: true

after_success:
  - mvn clean test jacoco:report coveralls:report