language: java
jdk:
  - oraclejdk8

services:
  - mongodb

sudo: false

before_install:
- mvn clean
- cd vokter-core
- mvn install -Dmaven.test.skip=true
- cd ../vokter-stemmers
- mvn test
- cd ../vokter-readers
- mvn test
- cd ../
- mvn test

install: true

after_success:
- cd vokter-core
 - mvn jacoco:report coveralls:report